package drl; 
import com.noob.fact.JudgeModel;
rule "ruleTest: test rule1"
when $judgeResult: JudgeModel(  Integer.parseInt(map.get("code1")) > 3 ||  Integer.parseInt(map.get("code2")) == 4 ||  Integer.parseInt(map.get("code3")) < 5 ||  (Integer.parseInt( map.get("code4")) >= 1 &&  Integer.parseInt(map.get("code4") ) <= 10 ))
then
System.out.print("test rule1");
$judgeResult.setSuccess(true);
end
